const ActionTypes = {
  FETCH_ARTICLES_FAILED: 'FETCH_ARTICLES_FAILED',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',

  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILED: 'PASSWORD_RESET_FAILED',

};

export default ActionTypes;
export const FACEBOOK_SIGNIN_SUCCESS = 'FACEBOOK_SIGNIN_SUCCESS';

export const FACEBOOK_SIGNIN_FAIL = 'FACEBOOK_SIGNIN_FAIL';

export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';

export const GOOGLE_SIGNIN_FAIL = 'GOOGLE_SIGNIN_FAIL';
